# Generated by Django 4.2.7 on 2025-09-04 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número de lote')),
                ('fecha_cosecha', models.DateField(verbose_name='Fecha de cosecha')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de recepción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso bruto (kg)')),
                ('peso_neto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso neto (kg)')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo total')),
                ('calidad', models.CharField(choices=[('PREMIUM', 'Premium'), ('PRIMERA', 'Primera'), ('SEGUNDA', 'Segunda'), ('TERCERA', 'Tercera')], default='PRIMERA', max_length=20, verbose_name='Calidad')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('PROCESADO', 'Procesado'), ('EMPACADO', 'Empacado'), ('DESPACHADO', 'Despachado')], default='RECIBIDO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de reporte')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('tipo_reporte', models.CharField(choices=[('PRODUCCION', 'Producción'), ('COSTOS', 'Costos'), ('CALIDAD', 'Calidad'), ('INVENTARIO', 'Inventario'), ('EFICIENCIA', 'Eficiencia')], max_length=50, verbose_name='Tipo de reporte')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros del reporte en JSON', verbose_name='Parámetros')),
                ('datos_reporte', models.JSONField(default=dict, help_text='Datos generados del reporte', verbose_name='Datos del reporte')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERANDO', 'Generando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('archivo_generado', models.CharField(blank=True, max_length=500, null=True, verbose_name='Archivo generado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contacto_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto principal')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Calificación (1-5)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('FRUTAS', 'Frutas'), ('VERDURAS', 'Verduras'), ('GRANOS', 'Granos'), ('TUBERCULOS', 'Tubérculos'), ('OTROS', 'Otros')], default='OTROS', max_length=100, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('TON', 'Toneladas'), ('CAJAS', 'Cajas'), ('SACOS', 'Sacos'), ('UNIDADES', 'Unidades')], default='KG', max_length=20, verbose_name='Unidad de medida')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio base')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de proceso')),
                ('tipo_proceso', models.CharField(choices=[('LAVADO', 'Lavado'), ('SELECCION', 'Selección'), ('CORTE', 'Corte'), ('EMPAQUE', 'Empaque'), ('ETIQUETADO', 'Etiquetado'), ('CONTROL_CALIDAD', 'Control de calidad')], max_length=50, verbose_name='Tipo de proceso')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad entrada')),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad salida')),
                ('merma', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Merma')),
                ('costo_proceso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo proceso')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.lote', verbose_name='Lote')),
                ('operario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_operario', to=settings.AUTH_USER_MODEL, verbose_name='Operario')),
            ],
            options={
                'verbose_name': 'Proceso de producción',
                'verbose_name_plural': 'Procesos de producción',
                'db_table': 'procesos_produccion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de costo')),
                ('tipo_costo', models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('MANO_OBRA', 'Mano de obra'), ('INSUMOS', 'Insumos'), ('SERVICIOS', 'Servicios'), ('TRANSPORTE', 'Transporte'), ('EMPAQUE', 'Empaque'), ('OTROS', 'Otros')], max_length=50, verbose_name='Tipo de costo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo total')),
                ('fecha_costo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del costo')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de factura')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.lote', verbose_name='Lote')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.procesoproduccion', verbose_name='Proceso')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
                'db_table': 'costos',
                'ordering': ['-fecha_costo'],
            },
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de control')),
                ('fecha_control', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de control')),
                ('parametros_evaluados', models.JSONField(default=dict, help_text='JSON con parámetros evaluados: {color, tamaño, peso, etc}', verbose_name='Parámetros evaluados')),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CONDICIONAL', 'Condicional'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20, verbose_name='Resultado')),
                ('puntuacion', models.DecimalField(decimal_places=1, default=0, help_text='Puntuación de 0 a 10', max_digits=3, verbose_name='Puntuación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('acciones_correctivas', models.TextField(blank=True, null=True, verbose_name='Acciones correctivas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_inspector', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.lote', verbose_name='Lote')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.procesoproduccion', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Control de calidad',
                'verbose_name_plural': 'Controles de calidad',
                'db_table': 'control_calidad',
                'ordering': ['-fecha_control'],
            },
        ),
    ]
