# Generated by Django 4.2.7 on 2025-09-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_remove_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_category', models.TextField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=12, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_profile', models.TextField(blank=True)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('puerto', models.CharField(default='1433', max_length=255, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('server', models.CharField(max_length=255, null=True)),
                ('database', models.CharField(max_length=255, null=True)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('uid_pass', models.CharField(max_length=255, null=True)),
                ('driver', models.CharField(default='ODBC Driver 17 for SQL Server', max_length=255, null=True)),
                ('type_con', models.CharField(choices=[('Api', 'Api'), ('Server Sql', 'Server Sql')], default='Api', max_length=50, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('requested_verified', models.BooleanField(default=False)),
                ('avatar_profile', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_role', models.TextField(blank=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='costo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='costo',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='costo',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='costo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='procesoproduccion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='procesoproduccion',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='procesoproduccion',
            name='operario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ControlCalidad',
        ),
        migrations.DeleteModel(
            name='Costo',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='ProcesoProduccion',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
