# Generated by Django 4.2.7 on 2025-09-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_create_new_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_profile',
            field=models.TextField(blank=True, help_text='Avatar en formato base64'),
        ),
    ]
